const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const db = require('../db_adapter');
const auth = require('../middleware/auth');

// Register
// Register
router.post('/register', async (req, res) => {
  const { name, email: rawEmail, password } = req.body;
  console.log(`[AUTH] Register request received for: ${rawEmail}`);

  try {
    if (!name || !rawEmail || !password) {
      return res.status(400).json({ message: 'MISSING REQUIRED FIELDS' });
    }

    const email = rawEmail.trim().toLowerCase();
    
    // Check if user already exists
    const existingUser = await db.users.findOne({ email });
    if (existingUser) {
      console.warn(`[AUTH] Register failed: Email ${email} already exists`);
      return res.status(400).json({ message: 'NODE ALREADY INDEXED' });
    }

    // Hash password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    // Insert user (ID will be auto-generated by model default)
    const user = await db.users.insert({ 
      name: name.trim(), 
      email, 
      password: hashedPassword, 
      role: 'pending',
      linkedChildren: [] 
    });

    console.log(`[AUTH] New node synthesized: ${user._id}`);

    const token = jwt.sign(
      { id: user._id, role: user.role }, 
      process.env.JWT_SECRET || 'neural_secret_key'
    );

    res.json({ 
      token, 
      user: { 
        id: user._id, 
        name: user.name, 
        email: user.email, 
        role: user.role,
        studentCode: user.studentCode || ''
      } 
    });
  } catch (err) {
    console.error(`[AUTH FATAL] Registration divergence: ${err.message}`);
    res.status(500).json({ 
      message: 'SYNTHESIS ERROR', 
      error: err.message,
      tip: 'Check if database connection is active and IP is whitelisted'
    });
  }
});

// Login
router.post('/login', async (req, res) => {
  const { email: rawEmail, password } = req.body;
  
  try {
    if (!rawEmail || !password) {
      return res.status(400).json({ message: 'CREDENTIALS REQUIRED' });
    }

    const email = rawEmail.trim().toLowerCase();
    console.log(`[AUTH] Login attempt: ${email}`);

    const user = await db.users.findOne({ email });
    if (!user) {
      console.warn(`[AUTH] Login failed: User ${email} not found`);
      return res.status(400).json({ message: 'NODE NOT FOUND' });
    }

    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) {
      console.warn(`[AUTH] Login failed: Password mismatch for ${email}`);
      return res.status(400).json({ message: 'INVALID CREDENTIALS' });
    }

    console.log(`[AUTH] Login success: ${email} (${user.role})`);

    const token = jwt.sign(
      { id: user._id, role: user.role }, 
      process.env.JWT_SECRET || 'neural_secret_key'
    );

    res.json({ 
      token, 
      user: { 
        id: user._id, 
        name: user.name, 
        email: user.email, 
        role: user.role,
        studentCode: user.studentCode || ''
      } 
    });
  } catch (err) {
    console.error(`[AUTH FATAL] Login error: ${err.stack}`);
    res.status(500).json({ 
      message: 'AUTHORIZATION ERROR', 
      error: err.message 
    });
  }
});

// Update Role (Onboarding)
router.post('/role', auth, async (req, res) => {
  const { role } = req.body;
  console.log(`[AUTH] Role update request for ${req.user.id}: ${role}`);

  try {
    if (!['student', 'parent'].includes(role)) {
      return res.status(400).json({ message: 'INVALID ROLE PROTOCOL' });
    }

    const updates = { role };
    
    // Generate unique student code if role is student
    if (role === 'student') {
      let unique = false;
      let code = '';
      while (!unique) {
        code = 'STU-' + Math.random().toString(36).substr(2, 5).toUpperCase();
        const existing = await db.users.findOne({ studentCode: code });
        if (!existing) unique = true;
      }
      updates.studentCode = code;
      console.log(`[AUTH] Generated student code: ${code}`);
    }

    const user = await db.users.update(req.user.id, updates);
    
    if (!user) {
      return res.status(404).json({ message: 'USER NODE NOT FOUND' });
    }

    res.json({ 
      message: 'IDENTITY SYNTHESIZED', 
      user: { 
        id: user._id, 
        name: user.name, 
        role: user.role, 
        studentCode: user.studentCode || '' 
      } 
    });
  } catch (err) {
    console.error(`[AUTH FATAL] Role update error: ${err.message}`);
    res.status(500).json({ message: 'DIVERGENCE ERROR', error: err.message });
  }
});

// Get Current User Status & Restrictions
router.get('/status', auth, async (req, res) => {
  try {
    const user = await db.users.findById(req.user.id);
    if (!user) return res.status(404).json({ message: 'NODE NOT FOUND' });

    let restrictions = null;
    if (user.role === 'student') {
      const link = await db.parent_student_links.findOne({ studentId: user._id });
      if (link) {
        restrictions = link.restrictions;
      }
    }

    res.json({
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        studentCode: user.studentCode
      },
      restrictions
    });
  } catch (err) {
    res.status(500).json({ message: 'STATUS CHECK FAILED', error: err.message });
  }
});

// Sync full dashboard state
router.post('/state', auth, async (req, res) => {
  try {
    const { state } = req.body;
    await db.users.update(req.user.id, { dashboardState: state });
    res.json({ message: 'NEURAL STATE SYNCHRONIZED' });
  } catch (err) {
    res.status(500).json({ message: 'SYNC ERROR', error: err.message });
  }
});

module.exports = router;
